services:
  postgres:
    image: postgres:17.2-alpine3.20
    container_name: virtualbookstore_postgresql
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=virtualbookstore_password
      - POSTGRES_USER=virtualbookstore_user
      - POSTGRES_DB=virtualbookstore
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - virtualbookstore_network
      
networks:
  virtualbookstore_network:
    driver: bridge