services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynet
    depends_on:
      - api
  api:
    image: thiagochfc/virtualbookstore.webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    networks:
      - mynet
      
networks:
  mynet:
    driver: bridge