<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1"/>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>ef1480ab-ff96-4d33-ba49-a8aa1127404a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1"/>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions" Version="9.6.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApi\VirtualBookstore.WebApi.csproj"/>
  </ItemGroup>

</Project>
